### ISSUE TITLE
gitにあげられない

### ISSUE THREAD

**Issue by mmng-a** [mcasashi-aso/twoLine#3]
<img width="570" alt="2017-06-26 11 18 13" src="https://user-images.githubusercontent.com/29685158/27522478-55b352e6-5a61-11e7-9613-644f2fee3340.png">

**Comment by s11y** [comment]
コミットメッセージつけずにコミットしたから、githubのコミットの履歴とMacのコミットの履歴が変わってるのかも

`git push -f origin master`
で強制的に更新してみたら、githubのコードはmacのコードと同じになるか試してみて

**Comment by mmng-a** [comment]
更新できた
ありがとう
